### ISSUE TITLE
Is't possible to change the min api to 14?

### ISSUE THREAD

**Issue by tuhin10** [SpongeBobSun/PoorEdit#1]

**Comment by SpongeBobSun** [comment]
The sample app may require a higher api level because it's using `appcompat` and `design` package.
But the PoorEdit lib may accept 14 as minimum api level. Because it doesn't use any of the fancy packages currently. 
Since I don't have a device which firmware is 4.0.x, so I can not test it right now. 
Thanks.

**Comment by tuhin10** [comment]
@SpongeBobSun  thanx.
